[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.lint]
select = [
  "B",    # bugbear
  "C4",   # comprehensions
  "C90",  # mccabe
  "D",    # docstrings
  "E",    # flake8
  "F",    # flake8
  "W",    # flake8
  "S",    # bandit
  "N",    # pep8-naming
  "I",    # isort
  "ANN",  # annotations and typing
  "T20",  # print statements
  "ARG",  # unused arguments
]
ignore = [
  "D100",
  "D205",
  "D415",
]
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "venv",
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
known-first-party = ["lib"]

[tool.ruff.format]
quote-style = "double"
