name: CI

on: [push, pull_request]

jobs:
  CI:
    name: Launching CI
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Set up pip cache
        uses: actions/cache@v3.3.2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: venv-${{ env.python-version }}-${{ hashFiles('pyproject.toml') }}

      - name: Set Poetry Path
        run: echo "/home/runner/.local/bin/" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry run pip install --upgrade pip
          poetry install

      - name: Run Pre commit hooks
        run: poetry run pre-commit run --all-files --hook-stage pre-push --show-diff-on-failure

      - name: Unit tests with pytest
        run: poetry run pytest tests  -s -vv --cov=lib --cov-config=./tests/.coveragerc --cov-report=term-missing --cov-fail-under=10

      - name: Validate configs
        run: poetry run python lib/validate_configs.py
